{% set name = "napari-folder-browser" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-folder-browser-{{ version }}.tar.gz
  sha256: c7144f8c0b321a30b64ad58928ed2efe65029f19670f0a650070506ae4551b76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari-plugin-engine >=0.1.4
    - napari-tools-menu
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - napari_folder_browser
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/haesleinhuepf/napari-folder-browser
  summary: Browse folders of images and open them using double-click
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
